<!DOCTYPE html>
<html>
<head>
    <title>Roman Urdu to Urdu Translator</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-5">Roman Urdu to Urdu Translator</h1>
        
        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST">
            <div class="form-group mt-4">
                <label for="text">Enter Roman Urdu Text:</label>
                <textarea class="form-control" name="text" rows="5" cols="40"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Translate</button>
        </form>
    </div>
    <?php
    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        $text = $_POST['text'];
        //hammaad
        // Define the translations for Roman Urdu characters
        $translations = array(
            'a' => 'ا',
            'b' => 'ب',
            'c' => 'س',
            'd' => 'د',
            'e' => 'ع',
            'f' => 'ف',
            'g' => 'گی',
            'h' => 'ہ',
            'i' => 'ی',
            'j' => 'ج',
            'k' => 'ک',
            'l' => 'ل',
            'm' => 'م',
            'n' => 'ن',
            'o' => 'ہ',
            'p' => 'پ',
            'q' => 'ق',
            'r' => 'ر',
            's' => 'ص',
            't' => 'ت',
            'u' => 'ء',
            'v' => 'چ',
            'w' => 'و',
            'x' => 'کس',
            'y' => 'ی',
            'z' => 'ز',
            'mm' => 'م',
            'hammad' => 'حماد',
            'mu' => 'م',
            'ha' => 'ھے',
            'aa' => 'آ',
            'ayesha' => 'عائشہ',
            '?' => '؟',
            'hayal' => 'ہایال',
            'mughal' => 'مغل',
            'tu' => 'تو',
            'to' => 'تو',
            'wa' => 'و',
            'nhi' => 'نہیں',
            'roky' => 'رکے',
            'wahin' => 'وہیں',
            'simt' => 'سمٹ',
            'jai' => 'جائے',
            'smjhny' => 'سمجھنے',
            'ma' => 'میں',
            'bss' => 'بس',
            'ik' => 'اک',
            'lafz' => 'لفظ',
            'kahani' => 'کہانی',
            'lgy' => 'لگے',
            'chot' => 'چھوٹ',
            'jny' => 'جانے',
            'bh' => 'بھ',
            'zindgi' => 'زندگی',
            'kuch' => 'کچھ',
            'khamoshiyun' => 'خاموشیوں',
            'ky' => 'کے',
            'gy' => 'گے',
            'khu' => 'خ',
            'hun' => 'ہوں',
            'wa' => 'وا',
            'izhar' => 'اظہار',
            'nazar' => 'نظر',
            'krny' => 'کرنے',
            'musam' => 'موسم',
            'mar' => 'مار',
            'ni' => 'نہیں',
            'ho' => 'ہو',
            'ankho' => 'آنکھوں',
            'shayd' => 'شاید',
            'sb' => 'سب',
            'kh' => 'کہہ',
            'gya' => 'گیا',
            'kyu' => 'کیوں',
            'savaira' => 'سویرا',
            'ny' => 'نے',
            'sy' => 'سے',
            'ly' => 'لے',
            'khud' => 'خود',
            'chiti' => 'چٹھی',
            'lik' => 'لکھ',
            'lo' => 'لوں',
            'ch' => 'چ',
            'chal' => 'چل',
            'kya' => 'کیا',
            'yun' => 'یوں',
            'dukhta' => 'دکھتا',
            'di' => 'د',
            'ay' => 'ے',
            'ga' => 'گا',
            'zair' => 'زیر',
            'kra' => 'کرے',
            'pal' => 'پل',
            'mil' => 'مل',
            'waqt' => 'وقت',
            'dheray' => 'دھیرے',
            'say' => 'سے',
            'da' => 'دے',
            'jo' => 'جو',
            'te' => 'تی',
            'ha' => 'ہے',
            'bi' => 'بی',
            'kul' => 'کل',
            'th' => 'ٹھ',
            'ee' => 'ی',
            'nh' => 'نھ',
            'ph' => 'پھ',
            'sh' => 'ش',
            'shad' => 'شد',
            'dh' => 'دھ',
            'ch' => 'چ',
            'lo' => 'لو',
            'hish' => 'ہش',
            'que' => 'کوئ',
            'tt' => 'ٹ',
            'quetta' => 'کوئٹہ',
            'kar' => 'کر',
            'guj' => 'گج',
            'su' => 'س',
            'no' => 'نو',
            'han' => 'ہاں',
            'kah' => 'کہ',
            'an' => 'اں',
            'chalo' => 'چلو',
            'ua' => 'وا',
            'bht' => 'بہت',
            'ai' => 'آئی',
            'me' => 'می',
            'yaken' => 'یقین',
            'kahin' => 'کہیں',
            'tuj' => 'تجھ',
            'py' => 'پہ',
            'bs' => 'بس',
            'hy' => 'ہے',
            'joo' => 'جوں',
            'th' => 'تھ',
            'tham' => 'تھم',
            'gai' => 'گئے',
            'shyd' => 'شاید',
            'mus' => 'مس',
            'kur' => 'کر',
            'ana' => 'انا',
            'subha' => 'صبح',
            'in' => 'ان',
            'tzar' => 'تظار',
            'ro' => 'رو',
            'je' => 'جی',
            'nazro' => 'نظروں',
            'dai' => 'دی',
            'kh' => 'کھ',
            'kas' => 'قس',
            'am' => 'م',
            'ry' => 'رے',
            'na' => 'نا',
            'bichar' => 'بچھڑ',
            'pi' => 'پی',
            'ni' => 'نی',
            'chia' => 'چاہئیے',
            'ir' => 'ر',
            'ya' => 'یہ',
            'acha' => 'اچھا',
            'lam' => 'لم',
            'lambi' => 'لمبی',
            'cho' => 'چو',
            'kam' => 'کام',
            'sk' => 'سک',
            'is' => 'اس',
            'ni' => 'نہیں',
            'nik' => 'نک',
            'ao' => 'او',
            'asad' => 'اسد',
            'ali' => 'علی',
            'ahmad' => 'احمد',
            'ishq' => 'عشق',
            'and' => 'اند',
            'khei' => 'خی',
        );
        
        // Translate the Roman Urdu text
        $urduText = strtr($text, $translations);
        
        // Output the translated Urdu text
        echo '<div class="alert alert-info mt-3">Translated Urdu Text: ' . $urduText . '</div>';
    }
    ?>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>
